/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.controladorUsuario;
import Modelos.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Almatron
 */
public final class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        iconoFormulario();
        iconosLogin();
        txtUsuario.setText("Administrador");
        //txtContrasenia.setText("admin2023");

    }
    Usuario usuario;
    public void iconoFormulario() {
        URL url = getClass().getResource("/Imagenes/login.png");
        ImageIcon icono_formulario = new ImageIcon(url);
        setIconImage(icono_formulario.getImage());
    }

    public void iconosLogin() {
        ImageIcon logo;
        logo = new ImageIcon(getClass().getResource("/Imagenes/login.png"));
        Icon icono = new ImageIcon(logo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH));
        lblLogo.setIcon(icono);

        ImageIcon image_usuario;
        image_usuario = new ImageIcon(getClass().getResource("/Imagenes/usuario3.png"));
        Icon icono_usuario = new ImageIcon(image_usuario.getImage().getScaledInstance(lblUsuarioIcono.getWidth(), lblUsuarioIcono.getHeight(), Image.SCALE_SMOOTH));
        lblUsuarioIcono.setIcon(icono_usuario);

        ImageIcon image_contrasenia;
        image_contrasenia = new ImageIcon(getClass().getResource("/Imagenes/contrasenia3.png"));
        Icon icono_contrasenia = new ImageIcon(image_contrasenia.getImage().getScaledInstance(lblContraseniaIcono.getWidth(), lblContraseniaIcono.getHeight(), Image.SCALE_SMOOTH));
        lblContraseniaIcono.setIcon(icono_contrasenia);
    }

    public void btnAceptarLblEntrar() {
        ImageIcon lblEntrarIcono;
        lblEntrarIcono = new ImageIcon(getClass().getResource("/Imagenes/aceptar.png"));
        Icon icono_entrar = new ImageIcon(lblEntrarIcono.getImage().getScaledInstance(lblEntrar.getWidth(), lblEntrar.getHeight(), Image.SCALE_SMOOTH));
        lblEntrar.setIcon(icono_entrar);

        btnIngresar.setBackground(new Color(44, 157, 29));
    }

    public void btnAceptarlblEntrar_salir() {
        lblEntrar.setIcon(null);
        btnIngresar.setBackground(Color.white);
    }

    public void btnsalirLblEntrar() {
        ImageIcon lblSalirIcono;
        lblSalirIcono = new ImageIcon(getClass().getResource("/Imagenes/cerrar.png"));
        Icon icono_salir = new ImageIcon(lblSalirIcono.getImage().getScaledInstance(lblSalir.getWidth(), lblSalir.getHeight(), Image.SCALE_SMOOTH));
        lblSalir.setIcon(icono_salir);

        btnSalir.setBackground(new Color(152, 31, 31));
    }

    public void btnASalirlblSalir_salir() {
        lblSalir.setIcon(null);
        btnSalir.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioTexto = new javax.swing.JLabel();
        lblContraseniaTexto = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblTituloLogin = new javax.swing.JLabel();
        lblTituloLogin2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblContraseniaIcono = new javax.swing.JLabel();
        lblUsuarioIcono = new javax.swing.JLabel();
        lblEntrar = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        lblSalir = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso al sistema de inventario");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(369, 443));
        setResizable(false);
        getContentPane().setLayout(null);

        lblUsuarioTexto.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblUsuarioTexto.setText("Usuario:");
        getContentPane().add(lblUsuarioTexto);
        lblUsuarioTexto.setBounds(20, 250, 80, 30);

        lblContraseniaTexto.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblContraseniaTexto.setText("Contraseña:");
        getContentPane().add(lblContraseniaTexto);
        lblContraseniaTexto.setBounds(20, 290, 110, 30);

        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblLogo);
        lblLogo.setBounds(110, 90, 140, 130);

        lblTituloLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lblTituloLogin.setText("SISTEMA DE INVENTARIO");
        getContentPane().add(lblTituloLogin);
        lblTituloLogin.setBounds(20, 10, 330, 40);

        lblTituloLogin2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblTituloLogin2.setText("Escuela Delia IBarra");
        getContentPane().add(lblTituloLogin2);
        lblTituloLogin2.setBounds(90, 60, 210, 21);

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(150, 350, 100, 50);

        lblContraseniaIcono.setAlignmentY(0.0F);
        lblContraseniaIcono.setMaximumSize(new java.awt.Dimension(9, 9));
        lblContraseniaIcono.setMinimumSize(new java.awt.Dimension(9, 9));
        lblContraseniaIcono.setPreferredSize(new java.awt.Dimension(9, 9));
        getContentPane().add(lblContraseniaIcono);
        lblContraseniaIcono.setBounds(310, 290, 30, 30);
        getContentPane().add(lblUsuarioIcono);
        lblUsuarioIcono.setBounds(310, 250, 30, 30);
        getContentPane().add(lblEntrar);
        lblEntrar.setBounds(290, 356, 50, 40);

        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContrasenia);
        txtContrasenia.setBounds(130, 290, 180, 30);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(130, 250, 180, 30);

        btnIngresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnIngresar.setText("Entrar");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(30, 350, 102, 50);
        getContentPane().add(lblSalir);
        lblSalir.setBounds(290, 356, 50, 40);

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpeg"))); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(-3, -4, 370, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        // TODO add your handling code here:
        btnAceptarLblEntrar();
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        // TODO add your handling code here:
        btnAceptarlblEntrar_salir();
    }//GEN-LAST:event_btnIngresarMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnsalirLblEntrar();
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        btnASalirlblSalir_salir();
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        controladorUsuario controladorUs = new controladorUsuario();
      
        char[] passwordChars = txtContrasenia.getPassword();
        String password = new String(passwordChars);
        try {
            if (controladorUs.login(txtUsuario.getText(), password)) {
                 usuario =  controladorUs.buscarUsuario(txtUsuario.getText());
                frmPrincipal formPrincipal = new frmPrincipal(usuario);
                formPrincipal.setVisible(true);
                dispose();
                //frmLogin.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
            }

        } catch (SQLException ex) {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblContraseniaIcono;
    private javax.swing.JLabel lblContraseniaTexto;
    private javax.swing.JLabel lblEntrar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JLabel lblTituloLogin2;
    private javax.swing.JLabel lblUsuarioIcono;
    private javax.swing.JLabel lblUsuarioTexto;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
