/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.funcionesAux;
import Controladores.llenarArticulos;
import Controladores.llenarCombos;
import Modelos.Usuario;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JToggleButton;

/**
 *
 * @author Almatron
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        iconoFormulario();
       
    }

    private Usuario usuario;

    public frmPrincipal(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        iconoFormulario();
         lblUsuarioLogeado.setText("Usuario: " + usuario.getNombreDeUsuario());
    }

    public void iconoFormulario() {
        URL url = getClass().getResource("/Imagenes/login.png");
        ImageIcon icono_formulario = new ImageIcon(url);
        setIconImage(icono_formulario.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlMenuLateral = new javax.swing.JPanel();
        lblTituloMenu = new javax.swing.JLabel();
        btnArticulos = new javax.swing.JToggleButton();
        btnUsuarios = new javax.swing.JToggleButton();
        btnTipoArticulo = new javax.swing.JToggleButton();
        btnSalir = new javax.swing.JButton();
        lblUsuarioLogeado = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JToggleButton();
        pnlContenedor = new javax.swing.JPanel();
        pnlPaneles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de inventario Delia Ibarra");

        pnlMenuLateral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTituloMenu.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblTituloMenu.setText("MENÚ DEL SISTEMA");

        btnArticulos.setBackground(new java.awt.Color(204, 204, 204));
        btnArticulos.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario1.png"))); // NOI18N
        btnArticulos.setText("Artículos");
        btnArticulos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnArticulos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnArticulosItemStateChanged(evt);
            }
        });
        btnArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticulosActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        btnUsuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnUsuariosItemStateChanged(evt);
            }
        });
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnTipoArticulo.setBackground(new java.awt.Color(204, 204, 204));
        btnTipoArticulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnTipoArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tipos.png"))); // NOI18N
        btnTipoArticulo.setText("<html>Tipo de <br>\nArtículo</html>");
        btnTipoArticulo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTipoArticulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnTipoArticuloItemStateChanged(evt);
            }
        });
        btnTipoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoArticuloActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setActionCommand("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblUsuarioLogeado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuarioLogeado.setText("jLabel1");

        btnHistorial.setBackground(new java.awt.Color(204, 204, 204));
        btnHistorial.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial.png"))); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHistorial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnHistorialItemStateChanged(evt);
            }
        });
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLateralLayout = new javax.swing.GroupLayout(pnlMenuLateral);
        pnlMenuLateral.setLayout(pnlMenuLateralLayout);
        pnlMenuLateralLayout.setHorizontalGroup(
            pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLateralLayout.createSequentialGroup()
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsuarioLogeado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuLateralLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTipoArticulo)
                            .addGroup(pnlMenuLateralLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addGap(40, 40, 40))
                            .addComponent(lblTituloMenu)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );
        pnlMenuLateralLayout.setVerticalGroup(
            pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLateralLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTituloMenu)
                .addGap(28, 28, 28)
                .addComponent(btnArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(btnTipoArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(lblUsuarioLogeado)
                .addContainerGap())
        );

        pnlContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlPaneles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPaneles.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        getContentPane().add(pnlFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        pnlUsuario pUsuario = new pnlUsuario();
        JScrollPane scrollPane = new JScrollPane(pUsuario);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        //pnlPaneles.setLayout(new BorderLayout());
        pnlPaneles.removeAll();
        pnlPaneles.add(scrollPane);
        pnlPaneles.repaint();
        pnlPaneles.revalidate();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnTipoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoArticuloActionPerformed
        // TODO add your handling code here:
         pnlTipoArticulo pTipoArticulo = new pnlTipoArticulo( usuario);
        JScrollPane scrollPane = new JScrollPane(pTipoArticulo);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        //pnlPaneles.setLayout(new BorderLayout());
        pnlPaneles.removeAll();
        pnlPaneles.add(scrollPane);
        pnlPaneles.repaint();
        pnlPaneles.revalidate();
        
        
    }//GEN-LAST:event_btnTipoArticuloActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        // TODO add your handling code here:
        try {
        pnlArticulos pArticulos = new pnlArticulos(usuario);
        JScrollPane scrollPane = new JScrollPane(pArticulos);
//       
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
//        
        pnlPaneles.removeAll();
        pnlPaneles.add(scrollPane);
        pnlPaneles.repaint();
        pnlPaneles.revalidate();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btnArticulosActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        pnlHistorial pHistorial = new pnlHistorial();
        JScrollPane scrollPane = new JScrollPane(pHistorial);
//       
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
//        
        pnlPaneles.removeAll();
        pnlPaneles.add(scrollPane);
        pnlPaneles.repaint();
        pnlPaneles.revalidate();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnHistorialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnHistorialItemStateChanged
        // TODO add your handling code here:
        int estado = evt.getStateChange();
                if(estado == evt.SELECTED){
                    btnArticulos.setSelected(false);
                    btnTipoArticulo.setSelected(false);
                    btnUsuarios.setSelected(false);
                }
    }//GEN-LAST:event_btnHistorialItemStateChanged

    private void btnArticulosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnArticulosItemStateChanged
        // TODO add your handling code here:
        int estado = evt.getStateChange();
                if(estado == evt.SELECTED){
                    btnHistorial.setSelected(false);
                    btnTipoArticulo.setSelected(false);
                    btnUsuarios.setSelected(false);
                }
    }//GEN-LAST:event_btnArticulosItemStateChanged

    private void btnUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnUsuariosItemStateChanged
        // TODO add your handling code here:
        int estado = evt.getStateChange();
                if(estado == evt.SELECTED){
                    btnHistorial.setSelected(false);
                    btnTipoArticulo.setSelected(false);
                   btnArticulos.setSelected(false);
                }
    }//GEN-LAST:event_btnUsuariosItemStateChanged

    private void btnTipoArticuloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnTipoArticuloItemStateChanged
        // TODO add your handling code here:
        int estado = evt.getStateChange();
                if(estado == evt.SELECTED){
                    btnHistorial.setSelected(false);
                    btnArticulos.setSelected(false);
                    btnUsuarios.setSelected(false);
                }
    }//GEN-LAST:event_btnTipoArticuloItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnArticulos;
    private javax.swing.JToggleButton btnHistorial;
    private javax.swing.JButton btnSalir;
    private javax.swing.JToggleButton btnTipoArticulo;
    private javax.swing.JToggleButton btnUsuarios;
    private javax.swing.JLabel lblTituloMenu;
    private javax.swing.JLabel lblUsuarioLogeado;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlMenuLateral;
    private javax.swing.JPanel pnlPaneles;
    // End of variables declaration//GEN-END:variables
}
