/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controladores.controladorHistorial;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Almatron
 */
public final class pnlHistorial extends javax.swing.JPanel {

    /**
     * Creates new form pnlHistorial
     */
    public pnlHistorial() {
        initComponents();
        tablaHistorial();
    }
    DefaultTableModel tabla = new DefaultTableModel();
    controladorHistorial controladorHist = new controladorHistorial();
    public void tablaHistorial() {
        tabla = controladorHist.llenarTablaHistorial(controladorHist.listarHistorial());
        tbHistorial.setModel(tabla);
        tbHistorial.getTableHeader().setReorderingAllowed(false);
        tbHistorial.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbHistorial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        tbHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbHistorial);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setText("HISTORIAL DE MODIFICACIONES");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHistorial;
    // End of variables declaration//GEN-END:variables
}
